### PR TITLE
Update functional.py

### PR DESCRIPTION
**Pull request by liyown**
Optimized for slow segmentation of data when the Dilliclet coefficient is small，According to this issue #230, but it might be difficult to replicate the results reported in the original paper.

### CODE REVIEW

**Comment by liyown** [comment]
In the code, if the number of samples for a category is 0, it will result in a process of randomly re-selecting the category. The code adds an exception handling mechanism to ensure that sample selection continues even if the number of samples for a category is 0. For example, when the sample number of a class is 0, a class with a non-zero sample number is randomly selected for sample selection.

**Comment by AgentDS** [comment]
Hi, Sorry for the late reply. 
Could you please rename the new version of the function as `client_inner_dirichlet_partition_faster`, and keep the old version of the function with the old name? so we can keep both versions for this function.

**Comment by liyown** [comment]
Modified

**Comment by AgentDS** [comment]
Thank you very much!

**Pull request merged**
